linters:
  enable:
    - cyclop
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gomnd
    - gosec
    - lll
    - makezero
    - nakedret
    - nestif
    - nilerr
    - noctx
    - prealloc
    - unconvert
    - unparam
    - wastedassign
    - wrapcheck
